---
#
# Packages
#
- name: add repository ppa:openjdk-r/ppa
  apt_repository: repo=ppa:openjdk-r/ppa update_cache=yes state=present

- name: install required packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - maven
    - openjdk-8-jdk

- name: update java alternatives
  command: update-java-alternatives -s {{ java_version }}

- name: clean package cache
  file: path=/var/lib/apt/lists/ state=absent

#
# Kepler
#
- name: install kepler 2.5
  unarchive: src={{ kepler_url }} dest=/usr/local copy=no keep_newer=yes

- name: prepare kepler launcher in menu which uses correct environment variables
  template: src=kepler.j2 dest=/usr/bin/kepler mode="u=rwx,g=rx,o=rx"

- name: git-clone indigoclient and indigokepler
  git: repo={{ item.repo }} dest={{ item.dest }} version={{ item.ver }} clone=yes
  with_items:
    - { repo: "https://github.com/indigo-dc/indigoclient.git", dest: "/usr/local/indigoclient", ver: "{{ indigo_kepler_version }}" }
    - { repo: "https://github.com/indigo-dc/indigokepler.git", dest: "/usr/local/indigokepler", ver: "{{ indigo_kepler_version }}" }

- name: compile indigoclient
  command: mvn install chdir=/usr/local/indigoclient

- name: prepare indigokepler
  command: mvn initialize chdir=/usr/local/indigokepler

- name: compile indigokepler
  command: mvn install dependency:copy-dependencies -DoutputDirectory=target/indigo/lib/jar -DexcludeArtifactIds=ptolemy chdir=/usr/local/indigokepler

- name: install indigo module in kepler directory
  command: /bin/cp -r /usr/local/indigokepler/target/indigo {{ kepler_home }}/

- name: configure kepler to use indigo module
  lineinfile: dest={{ kepler_home }}/build-area/modules.txt insertbefore=BOF line=indigo

#
# User
#
- name: add new user {{ user }}
  user: name={{ user }} password={{ password_crypt }} shell=/bin/bash groups=adm,sudo

#
# Finalize
#
- name: create symbolic link
  file: src=/usr/local/indigokepler/workflows/ophidia dest=/home/{{ user }}/ophidia state=link
